### ISSUE TITLE
【无法使用】无法在以 root 身份运行的 WSL2 环境中启动 Container

### ISSUE THREAD

**Issue by Dragon1573** [xueyong-q/docker-nginx-php#1]
# 问题概述

WSL2 实例只有 `root` 用户作为唯一登录身份，在 VSCode 启动项目 Dev Container 环境时无法构建 Container ，提示 `root` 用户组已经存在。

# 环境信息

<details>
<summary>宿主环境</summary>

![image](https://user-images.githubusercontent.com/49941141/195511316-cd55754a-ebb2-41bc-8d8b-7125f4baefa0.png)

</details>
<details>
<summary>WSL2 环境</summary>

![image](https://user-images.githubusercontent.com/49941141/195511996-0a5788c7-b501-4889-b896-ebf2aabdb154.png)

</details>
<details>
<summary>VSCode 环境</summary>

![image](https://user-images.githubusercontent.com/49941141/195511752-2bd35386-cad4-4a56-a529-c8ba63627db7.png)

</details>
<details>
<summary>Docker for Windows 环境</summary>

![image](https://user-images.githubusercontent.com/49941141/195513233-7352d1d3-2a91-4d34-a223-18664bbec836.png)

![image](https://user-images.githubusercontent.com/49941141/195513293-451cc411-da71-42a7-b066-543f685bf841.png)

![image](https://user-images.githubusercontent.com/49941141/195513348-daade744-1c6d-4cef-91b3-dbe235625d49.png)

![image](https://user-images.githubusercontent.com/49941141/195513377-8ca7e842-7f0d-49d4-997b-b075f147d912.png)

</details>

# 复现方法

在 WSL2 执行以下命令：

```fish
➜  Documents gh repo clone xueyong-q/docker-nginx-php
Cloning into 'docker-nginx-php'...
remote: Enumerating objects: 1394, done.
remote: Counting objects: 100% (1394/1394), done.
remote: Compressing objects: 100% (1241/1241), done.
Receiving objects: 100% (1394/1394), 1.03 MiB | 64.00 KiB/s, done.
Resolving deltas: 100% (137/137), done.
remote: Total 1394 (delta 137), reused 1367 (delta 111), pack-reused 0
```

我们不需要使用到数据库，在 VSCode 打开 WSL2 项目路径，并注释 `.devcontainer/devcontainer.json` 第50行：

```jsonc
{
    // 将镜像添加到 database_app 网络
    "runArgs": [
        // "--network=database_app"
    ]
}
```

在 VSCode 运行 `Dev Container: Rebuild and Reopen folder in Container` ，等待 Docker Container 环境构建完成。

<details>
<summary>终端日志（节选）</summary>

```text
#0 146.3 Build complete.
#0 146.3 Don't forget to run 'make test'.
#0 146.3 
#0 146.3 + strip --strip-all modules/pcntl.so
#0 146.3 Installing shared extensions:     /usr/local/lib/php/extensions/no-debug-non-zts-20190902/
#0 146.4 find . -name \*.gcno -o -name \*.gcda | xargs rm -f
#0 146.4 find . -name \*.lo -o -name \*.o | xargs rm -f
#0 146.4 find . -name \*.la -o -name \*.a | xargs rm -f
#0 146.4 find . -name \*.so | xargs rm -f
#0 146.4 find . -name .libs -a -type d|xargs rm -rf
#0 146.4 rm -f libphp.la      modules/* libs/*
#0 146.8 groupadd: group 'root' already exists
------
ERROR: failed to solve: executor failed running [/bin/sh -c sed -ri 's/https?:\/\/.*\.debian\.org/https:\/\/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list     && apt-get update     && apt-get -y install --no-install-recommends apt-utils dialog 2>&1     && apt-get -y install git procps iproute2 lsb-release curl wget         vim zip libzip-dev mlocate lsof net-tools libfreetype6-dev         libjpeg62-turbo-dev libpng-dev make autoconf gcc g++ libpcre3-dev         libpcre3 openssl libssl-dev sudo jq gnupg2 ca-certificates     && /tmp/install-ext.sh && rm -f /tmp/install-ext.sh     && groupadd --gid $USER_GID $USERNAME     && useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME     && echo "${USERNAME} ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/${USERNAME}     && chmod 0440 /etc/sudoers.d/${USERNAME}     && mkdir -p /home/${USERNAME}/bin     && curl -o /home/${USERNAME}/bin/composer https://getcomposer.org/download/latest-stable/composer.phar     && chmod +x /home/${USERNAME}/bin/composer     && /home/${USERNAME}/bin/composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/     && mv /tmp/docker-app.sh /home/${USERNAME}/bin/docker-app     && mv /tmp/bashrc.sh /home/${USERNAME}/.bashrc     && echo "export PATH=\$PATH:\$HOME/.composer/vendor/bin" >> /home/${USERNAME}/.bashrc     && sed -ri "s/user.*=.*www-data/user = ${USERNAME}/g" /usr/local/etc/php-fpm.d/www.conf     && sed -ri "s/group.*=.*www-data/group = ${USERNAME}/g" /usr/local/etc/php-fpm.d/www.conf     && apt-get autoremove -y     && apt-get clean -y     && rm -rf /var/lib/apt/lists/*]: exit code: 9
[157985 ms] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.20.0-1665641046679/Dockerfile-with-features -t vsc-docker-nginx-php-33d95538b288df30123c9731e5ffddd7 --target dev_containers_target_stage --build-arg PHP_VERSION=7.4-fpm --build-arg USERNAME=root --build-arg USER_UID=1000 --build-arg LANG=C.UTF-8 --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.20.0-1665641046679 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /root/Documents/docker-nginx-php/.devcontainer/php
[157986 ms]     at Vse (/root/.vscode-remote-containers/dist/dev-containers-cli-0.255.3/dist/spec-node/devContainersSpecCLI.js:1869:1635)
[157987 ms]     at runMicrotasks (<anonymous>)
[157987 ms]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[157987 ms]     at async ZA (/root/.vscode-remote-containers/dist/dev-containers-cli-0.255.3/dist/spec-node/devContainersSpecCLI.js:1868:1973)
[157987 ms]     at async jO (/root/.vscode-remote-containers/dist/dev-containers-cli-0.255.3/dist/spec-node/devContainersSpecCLI.js:1868:901)
[157987 ms]     at async Xse (/root/.vscode-remote-containers/dist/dev-containers-cli-0.255.3/dist/spec-node/devContainersSpecCLI.js:1874:2030)
[157988 ms]     at async Uf (/root/.vscode-remote-containers/dist/dev-containers-cli-0.255.3/dist/spec-node/devContainersSpecCLI.js:1874:3193)
[157988 ms]     at async Cae (/root/.vscode-remote-containers/dist/dev-containers-cli-0.255.3/dist/spec-node/devContainersSpecCLI.js:1994:10350)
[157988 ms]     at async yae (/root/.vscode-remote-containers/dist/dev-containers-cli-0.255.3/dist/spec-node/devContainersSpecCLI.js:1994:10104)
[157996 ms] Exit code 1
[158004 ms] Command failed: /root/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/node /root/.vscode-remote-containers/dist/dev-containers-cli-0.255.3/dist/spec-node/devContainersSpecCLI.js up --workspace-folder /root/Documents/docker-nginx-php --workspace-mount-consistency cached --id-label devcontainer.local_folder=\\wsl.localhost\Ubuntu\root\Documents\docker-nginx-php --log-level debug --log-format json --config /root/Documents/docker-nginx-php/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[158004 ms] Exit code 1
```

</details>

[remoteContainers-2022-10-13T06-12-48.358Z.log](https://github.com/xueyong-q/docker-nginx-php/files/9771345/remoteContainers-2022-10-13T06-12-48.358Z.log)

**Comment by Dragon1573** [comment]
重新安装了 Ubuntu on WSL2 ，版本信息如下：

![image](https://user-images.githubusercontent.com/49941141/197463541-f5a52cb2-06ee-4be4-8425-e6f546afc2ca.png)

由于不再直接使用 `root` 作为登录身份，容器及其相关服务可以被正常启动。

- Dev Container 容器创建日志：[create.log](https://github.com/xueyong-q/docker-nginx-php/files/9849356/create.log)
- 容器创建后置日志：[postCreate.log](https://github.com/xueyong-q/docker-nginx-php/files/9849363/postCreate.log)

![image](https://user-images.githubusercontent.com/49941141/197464078-eec744d7-5866-44b4-a583-c07ec9264f06.png)

![image](https://user-images.githubusercontent.com/49941141/197464185-c00e0f89-0e0d-456c-abab-8207e59bc3d4.png)

![image](https://user-images.githubusercontent.com/49941141/197464375-ea21f4bf-f621-4b17-bcd8-f8bda20dc8a6.png)
